// <auto-generated />
namespace MyCreek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 新增字段 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(新增字段));
        
        string IMigrationMetadata.Id
        {
            get { return "201803170846103_新增字段"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
